spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:menu}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: ${CONNECTION_TIMEOUT_MS:30000}
      maximum-pool-size: ${CONNECTION_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Improved schema validation
        jdbc.time_zone: UTC
        id.new_generator_mappings: true
        # Better error messages for schema validation
        schema_validation.error_level: ERROR
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      repositories:
        enabled: ${ENABLE_REDIS_CACHE:true}
  cache:
    redis:
      time-to-live: ${CACHE_TTL_SECONDS:300}000

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: ${SWAGGER_TITLE:Menu Service API}
    description: ${SWAGGER_DESCRIPTION:API for dynamic personalized menu generation}
    version: ${SWAGGER_VERSION:1.0.0}
    contact:
      name: ${SWAGGER_CONTACT_NAME:Kava Team}
      email: ${SWAGGER_CONTACT_EMAIL:support@kava.com}

# External service configurations
services:
  analytics:
    url: ${ANALYTICS_SERVICE_URL:http://localhost:8081/api}
  user:
    url: ${USER_SERVICE_URL:http://localhost:8082/api}
  discount-engine:
    url: ${DISCOUNT_ENGINE_URL:http://localhost:8083/api}

# Feature flags
features:
  geo-targeting: ${ENABLE_GEO_TARGETING:true}
  dynamic-pricing: ${ENABLE_DYNAMIC_PRICING:true}

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.kava.menu: ${LOG_LEVEL:INFO}
  file:
    name: ${LOG_FILE_PATH:logs/menu-service.log}
